-- The bulk of the table is csv.
-- Make sure these lines are properly formatted comments.
-- The next line is    return [[
--- Watch out for the csv editor adding ;;;;
-- Line after that is the headings, without quotation marks
-- Final line is  ]]
--- Again, watch for the csv editor adding ;;;;
-- Group and subgroup aren't needed for the mod, but are a big help when looking for patterns.


return [[
badgeset;group;subgroup;name;type;badge
Englishmentalsbroken;intermediate-products;bob-bearings;iron-bearing;item;x1
Englishmentalsbroken;intermediate-products;bob-bearings;iron-bearing-ball;item;x1
mainbroken;intermediate-products;bob-bearings;iron-bearing;item;x1
mainbroken;intermediate-products;bob-bearings;iron-bearing-ball;item;x1
main;bio-processing-alien;bio-processing-alien-large;alien-artifact;item;x1
main;bio-processing-alien;bio-processing-alien-pre;alien-pre-artifact-base;item;x1
main;bio-processing-alien;bio-processing-alien-small;small-alien-artifact;item;x1
main;intermediate-products;bob-gears;iron-gear-wheel;item;x1
main;intermediate-products;bob-roboport-parts-antenna;roboport-antenna-1;item;x1
main;intermediate-products;bob-roboport-parts-door;roboport-door-1;item;x1
main;water-treatment;water-enrichment;liquid-water-semiheavy-1;fluid;x1
main;water-treatment;water-washing-fluid;water-viscous-mud;fluid;x1
mainbroken;combat;armor;light-armor;item;x1
Englishmentalsbroken;intermediate-products;bob-bearings;steel-bearing;item;x2
Englishmentalsbroken;intermediate-products;bob-bearings;steel-bearing-ball;item;x2
mainbroken;intermediate-products;bob-bearings;steel-bearing;item;x2
mainbroken;intermediate-products;bob-bearings;steel-bearing-ball;item;x2
main;intermediate-products;bob-gears;steel-gear-wheel;item;x2
main;intermediate-products;bob-roboport-parts-antenna;roboport-antenna-2;item;x2
main;intermediate-products;bob-roboport-parts-door;roboport-door-2;item;x2
main;water-treatment;water-enrichment;liquid-water-semiheavy-2;fluid;x2
main;water-treatment;water-washing-fluid;water-heavy-mud;fluid;x2
mainbroken;combat;armor;heavy-armor;item;x2
Englishmentalsbroken;intermediate-products;bob-bearings;brass-bearing;item;x3
Englishmentalsbroken;intermediate-products;bob-bearings;brass-bearing-ball;item;x3
main;intermediate-products;bob-gears;brass-gear-wheel;item;x3
main;intermediate-products;bob-roboport-parts-antenna;roboport-antenna-3;item;x3
main;intermediate-products;bob-roboport-parts-door;roboport-door-3;item;x3
main;water-treatment;water-enrichment;liquid-water-semiheavy-3;fluid;x3
main;water-treatment;water-washing-fluid;water-concentrated-mud;fluid;x3
mainbroken;combat;armor;modular-armor;item;x3
Englishmentalsbroken;intermediate-products;bob-bearings;cobalt-steel-bearing;item;x4
Englishmentalsbroken;intermediate-products;bob-bearings;cobalt-steel-bearing-ball;item;x4
main;intermediate-products;bob-bearings;cobalt-steel-bearing;item;x4
main;intermediate-products;bob-bearings;cobalt-steel-bearing-ball;item;x4
main;intermediate-products;bob-gears;cobalt-steel-gear-wheel;item;x4
main;intermediate-products;bob-roboport-parts-antenna;roboport-antenna-4;item;x4
main;intermediate-products;bob-roboport-parts-door;roboport-door-4;item;x4
main;water-treatment;water-enrichment;liquid-water-heavy;fluid;x4
main;water-treatment;water-washing-fluid;water-light-mud;fluid;x4
mainbroken;combat;armor;power-armor;item;x4
Englishmentalsbroken;intermediate-products;bob-bearings;titanium-bearing;item;x5
Englishmentalsbroken;intermediate-products;bob-bearings;titanium-bearing-ball;item;x5
mainbroken;intermediate-products;bob-bearings;titanium-bearing;item;x5
mainbroken;intermediate-products;bob-bearings;titanium-bearing-ball;item;x5
main;intermediate-products;bob-gears;titanium-gear-wheel;item;x5
main;water-treatment;water-washing-fluid;water-thin-mud;fluid;x5
mainbroken;combat;armor;power-armor-mk2;item;x5
Englishmentalsbroken;intermediate-products;bob-bearings;tungsten-bearing;item;x6
Englishmentalsbroken;intermediate-products;bob-bearings;tungsten-bearing-ball;item;x6
mainbroken;intermediate-products;bob-bearings;tungsten-bearing;item;x6
mainbroken;intermediate-products;bob-bearings;tungsten-bearing-ball;item;x6
main;intermediate-products;bob-gears;tungsten-gear-wheel;item;x6
mainbroken;combat;armor;bob-power-armor-mk3;item;x6
Englishmentalsbroken;intermediate-products;bob-bearings;nitinol-bearing;item;x7
Englishmentalsbroken;intermediate-products;bob-bearings;nitinol-bearing-ball;item;x7
mainbroken;intermediate-products;bob-bearings;nitinol-bearing;item;x7
mainbroken;intermediate-products;bob-bearings;nitinol-bearing-ball;item;x7
main;intermediate-products;bob-gears;nitinol-gear-wheel;item;x7
mainbroken;combat;armor;bob-power-armor-mk4;item;x7
mainbroken;combat;armor;bob-power-armor-mk5;item;x8
mainbroken;intermediate-products;bob-electronic-components;integrated-electronics;item;-
main;intermediate-products;bob-electronic-components;basic-electronic-components;item;-
main;intermediate-products;bob-electronic-components;electronic-components;item;-
main;intermediate-products;bob-electronic-components;processing-electronics;item;-
main;intermediate-products;bob-intermediates;rtg;item;-
main;petrochem-refining;petrochem-fuel;enriched-fuel;item;-
main;petrochem-refining;petrochem-fuel;nuclear-fuel;item;-
main;petrochem-refining;petrochem-fuel;rocket-booster;item;-
main;petrochem-refining;petrochem-fuel;rocket-fuel;item;-
main;petrochem-refining;petrochem-fuel;rocket-fuel-capsule;item;-
main;petrochem-refining;petrochem-fuel;rocket-oxidizer-capsule;item;-
main;petrochem-refining;petrochem-solids;insulated-cable;item;-
main;petrochem-refining;petrochem-solids;plastic-bar;item;-
main;petrochem-refining;petrochem-solids;rubber;item;-
main;bob-logistics;pipe;copper-pipe;item;1a
main;bob-logistics;pipe-to-ground;copper-pipe-to-ground;item;1a
main;bob-logistics;pipe;pipe;item;1b
main;bob-logistics;pipe-to-ground;pipe-to-ground;item;1b
main;bob-logistics;pipe;stone-pipe;item;1c
main;bob-logistics;pipe-to-ground;stone-pipe-to-ground;item;1c
main;bob-logistics;pipe;bronze-pipe;item;2a
main;bob-logistics;pipe-to-ground;bronze-pipe-to-ground;item;2a
main;bob-logistics;pipe;steel-pipe;item;2b
main;bob-logistics;pipe-to-ground;steel-pipe-to-ground;item;2b
main;bob-logistics;pipe;plastic-pipe;item;3a
main;bob-logistics;pipe-to-ground;plastic-pipe-to-ground;item;3a
main;bob-logistics;pipe;brass-pipe;item;3b
main;bob-logistics;pipe-to-ground;brass-pipe-to-ground;item;3b
main;bob-logistics;pipe;titanium-pipe;item;4a
main;bob-logistics;pipe-to-ground;titanium-pipe-to-ground;item;4a
main;bob-logistics;pipe;ceramic-pipe;item;4b
main;bob-logistics;pipe-to-ground;ceramic-pipe-to-ground;item;4b
main;bob-logistics;pipe;tungsten-pipe;item;4c
main;bob-logistics;pipe-to-ground;tungsten-pipe-to-ground;item;4c
main;bob-logistics;pipe;nitinol-pipe;item;5a
main;bob-logistics;pipe-to-ground;nitinol-pipe-to-ground;item;5a
main;bob-logistics;pipe;copper-tungsten-pipe;item;5b
main;bob-logistics;pipe-to-ground;copper-tungsten-pipe-to-ground;item;5b
main;bio-processing-alien;bio-puffer-5;bio-puffer-4;item;A
main;bio-processing-alien;bio-puffer-egg;bio-puffer-egg-4;item;A
main;petrochem-refining;petrochem-basic-fluids;gas-compressed-air;fluid;A
main;bio-processing-alien;bio-processing-alien-intermediate;alien-bacteria;item;AB
main;bio-processing-nauvis;bio-wood;solid-alienated-fertilizer;item;AF
main;angels-casting;angels-silver-casting;angels-roll-silver;item;Ag
main;angels-casting;angels-silver-casting;angels-wire-coil-silver;item;Ag
main;angels-casting;angels-silver-casting;angels-wire-silver;item;Ag
main;angels-casting;angels-silver-casting;liquid-molten-silver;fluid;Ag
main;angels-casting;angels-silver-casting;silver-plate;item;Ag
main;angels-smelting;angels-silver;cathode-silver;item;Ag
main;angels-smelting;angels-silver;ingot-silver;item;Ag
main;angels-smelting;angels-silver;pellet-silver;item;Ag
main;angels-smelting;angels-silver;processed-silver;item;Ag
main;angels-smelting;angels-silver;silver-nitrate;item;Ag
main;angels-smelting;angels-silver;silver-ore;item;Ag
main;angels-smelting;angels-silver;silver-oxide;item;Ag
main;angels-smelting;angels-silver;solid-sodium-silver-cyanide;item;Ag
main;bio-processing-alien;bio-processing-alien-intermediate;alien-goo;fluid;AG
Englishmentals;angels-casting;angels-aluminium-casting;aluminium-plate;item;Al
Englishmentals;angels-casting;angels-aluminium-casting;angels-roll-aluminium;item;Al
Englishmentals;angels-casting;angels-aluminium-casting;liquid-molten-aluminium;fluid;Al
Englishmentals;angels-smelting;angels-aluminium;alumina;item;Al
Englishmentals;angels-smelting;angels-aluminium;bauxite-ore;item;Al
Englishmentals;angels-smelting;angels-aluminium;ingot-aluminium;item;Al
Englishmentals;angels-smelting;angels-aluminium;pellet-aluminium;item;Al
Englishmentals;angels-smelting;angels-aluminium;processed-aluminium;item;Al
Englishmentals;angels-smelting;angels-aluminium;solid-aluminium-hydroxide;item;Al
Englishmentals;angels-smelting;angels-aluminium;solid-sodium-aluminate;item;Al
main;angels-casting;angels-aluminium-casting;aluminium-plate;item;Al
main;angels-casting;angels-aluminium-casting;angels-roll-aluminium;item;Al
main;angels-casting;angels-aluminium-casting;liquid-molten-aluminium;fluid;Al
main;angels-smelting;angels-aluminium;alumina;item;Al
main;angels-smelting;angels-aluminium;bauxite-ore;item;Al
main;angels-smelting;angels-aluminium;ingot-aluminium;item;Al
main;angels-smelting;angels-aluminium;pellet-aluminium;item;Al
main;angels-smelting;angels-aluminium;processed-aluminium;item;Al
main;angels-smelting;angels-aluminium;solid-aluminium-hydroxide;item;Al
main;angels-smelting;angels-aluminium;solid-sodium-aluminate;item;Al
main;bio-processing-alien;bio-processing-alien-intermediate;bio-alien-processed-meat;item;AM
main;petrochem-refining;petrochem-nitrogen-fluids;gas-ammonia;fluid;AM
main;bio-processing-alien;bio-processing-alien-intermediate;alien-spores;fluid;AS
Englishmentals;bio-processing-alien;bio-processing-paste;paste-gold;item;Au
main;angels-casting;angels-gold-casting;angels-roll-gold;item;Au
main;angels-casting;angels-gold-casting;angels-wire-coil-gold;item;Au
main;angels-casting;angels-gold-casting;gilded-copper-cable;item;Au
main;angels-casting;angels-gold-casting;gold-plate;item;Au
main;angels-casting;angels-gold-casting;liquid-molten-gold;fluid;Au
main;angels-smelting;angels-gold;cathode-gold;item;Au
main;angels-smelting;angels-gold;gold-ore;item;Au
main;angels-smelting;angels-gold;ingot-gold;item;Au
main;angels-smelting;angels-gold;liquid-chlorauric-acid;fluid;Au
main;angels-smelting;angels-gold;pellet-gold;item;Au
main;angels-smelting;angels-gold;powder-gold;item;Au
main;angels-smelting;angels-gold;processed-gold;item;Au
main;angels-smelting;angels-gold;solid-sodium-gold-cyanide;item;Au
main;bio-processing-alien;bio-processing-paste;paste-gold;item;Au
main;bio-processing-alien;bio-biter;biter-big;item;B
main;bio-processing-alien;bio-biter;biter-big-egg;item;B
main;bio-processing-alien;bio-biter;biter-queen-big;item;B
main;bio-processing-alien;bio-puffer-4;bio-puffer-3;item;B
main;bio-processing-alien;bio-puffer-egg;bio-puffer-egg-3;item;B
main;bio-processing-alien;bio-puffer-egg;bio-puffer-egg-shell;item;B
main;bio-processing-alien;bio-puffer-egg;bio-puffer-egg-shell-powder;item;B
main;bio-processing-vegetables;bio-processor-nutrient;solid-beans;item;B
main;bobs-gems;bio-biter-processing-crystal-full;crystal-full-blue;item;B
main;bobs-gems;bio-biter-processing-crystal-full;crystal-full-blue-cut;item;B
main;bobs-gems;bio-biter-processing-crystal-shard;crystal-shard-blue;item;B
main;bobs-gems;bio-biter-processing-crystal-shard;crystal-shard-blue-cut;item;B
main;bobs-gems;bio-biter-processing-crystal-splinter;crystal-splinter-blue;item;B
main;bobs-gems;bio-biter-processing-crystal-splinter;crystal-splinter-blue-cut;item;B
mainbroken;combat;ammo;firearm-magazine;item;B
main;bio-processing-vegetables;bio-plastic;liquid-cellulose-acetate;fluid;B1
main;bio-processing-vegetables;bio-plastic;liquid-propionic-acid;fluid;B2
main;bio-processing-vegetables;bio-processor-fermentation;gas-ethanol;fluid;B3
main;bio-processing-vegetables;bio-processor-fermentation;liquid-acetic-acid;fluid;B4
main;bio-processing-vegetables;bio-processor-fermentation;liquid-acetic-anhydride;fluid;B5
main;bio-processing-vegetables;bio-processor-fermentation;liquid-cellulose-acetate-mixture;fluid;B6
main;bio-processing-vegetables;bio-processor-fermentation;liquid-fermentation-raw;fluid;B7
Englishmentals;angels-casting;angels-alloys-casting;brass-alloy;item;Ba
Englishmentals;angels-casting;angels-alloys-casting;liquid-molten-brass;fluid;Ba
main;angels-casting;angels-alloys-casting;brass-alloy;item;Ba
main;angels-casting;angels-alloys-casting;liquid-molten-brass;fluid;Ba
main;intermediate-products;bob-intermediates;battery;item;Ba
main;petrochem-refining;petrochem-solids;blasting-charge;item;BC
main;bio-processing-nauvis;bio-liquor;liquid-black-liquor;fluid;Bk
main;intermediate-products;bob-electronic-boards;advanced-processing-unit;item;Bk
main;intermediate-products;bob-electronic-boards;cp-advanced-processing-board;item;Bk
main;intermediate-products;bob-electronic-boards;multi-layer-circuit-board;item;Bk
main;bio-processing-nauvis;bio-liquor;liquid-brown-liquor;fluid;Bn
main;bio-processing-nauvis;bio-processing-brown;solid-alginic-acid;item;Bn
main;intermediate-products;bob-electronic-boards;basic-circuit-board;item;Bn
main;resource-refinining;angels-ores;angels-ore6;item;Bo
main;resource-refinining;ore-processing-a;angels-ore6-crushed;item;Bo
main;resource-refinining;ore-processing-b;angels-ore6-chunk;item;Bo
main;resource-refinining;ore-processing-c;angels-ore6-crystal;item;Bo
main;resource-refinining;ore-processing-d;angels-ore6-pure;item;Bo
main;bio-processing-nauvis;bio-processing-brown;algae-brown;item;Br
Englishmentalsbroken;sct-science;sct-science-pack-3;chemical-science-pack;item;Bu
mainbroken;sct-science;sct-science-pack-3;chemical-science-pack;item;Bu
main;bio-processing-alien;bio-processing-alien-large;alien-artifact-blue;item;Bu
main;bio-processing-alien;bio-processing-alien-pre;alien-pre-artifact-blue;item;Bu
main;bio-processing-alien;bio-processing-alien-small;small-alien-artifact-blue;item;Bu
main;bio-processing-nauvis;bio-processing-blue;algae-blue;item;Bu
main;bio-processing-nauvis;bio-processing-blue;blue-cellulose-fiber;item;Bu
main;intermediate-products;bob-electronic-boards;cp-processing-board;item;Bu
main;intermediate-products;bob-electronic-boards;processing-unit;item;Bu
main;intermediate-products;bob-electronic-boards;superior-circuit-board;item;Bu
main;petrochem-refining;petrochem-catalysts;catalyst-metal-blue;item;Bu
main;resource-refinining;geode-processing-1;geode-blue;item;Bu
Englishmentals;angels-casting;angels-alloys-casting;bronze-alloy;item;Bz
Englishmentals;angels-casting;angels-alloys-casting;liquid-molten-bronze;fluid;Bz
main;angels-casting;angels-alloys-casting;bronze-alloy;item;Bz
main;angels-casting;angels-alloys-casting;liquid-molten-bronze;fluid;Bz
main;bio-processing-alien;bio-puffer-6;bio-puffer-5;item;C
main;bio-processing-alien;bio-puffer-egg;bio-puffer-egg-5;item;C
main;bio-processing-nauvis;bio-wood;solid-compost;item;C
main;bio-processing-vegetables;bio-processor-nutrient;solid-corn;item;C
main;petrochem-refining;petrochem-chlorine-fluids;liquid-hydrochloric-acid;fluid;C
main;petrochem-refining;petrochem-coal;solid-carbon;item;C
main;resource-refinining;processing-crafting;catalysator-green;item;C
main;resource-refinining;processing-crafting;filter-ceramic;item;C
main;water-treatment;water-cleaning-fluid;water-green-waste;fluid;C
main;intermediate-products;bob-robot-parts;robot-brain-construction;item;C1
main;petrochem-refining;petrochem-basic-fluids;gas-carbon-monoxide;fluid;C1
main;intermediate-products;bob-robot-parts;robot-brain-construction-2;item;C2
main;petrochem-refining;petrochem-basic-fluids;gas-carbon-dioxide;fluid;C2
main;intermediate-products;bob-robot-parts;robot-brain-construction-3;item;C3
main;intermediate-products;bob-robot-parts;robot-brain-construction-4;item;C4
main;petrochem-refining;petrochem-chlorine-fluids;gas-allylchlorid;fluid;CA
main;petrochem-refining;petrochem-sulfur;solid-calcium-chloride;item;CC
main;resource-refinining;ore-sorting-fluid;crystal-seedling;fluid;CD
main;angels-smelting;angels-stone;solid-cement;item;Ce
main;bio-processing-alien;bio-processing-alien-intermediate;crystal-enhancer;item;CE
main;petrochem-refining;petrochem-chlorine-fluids;gas-epichlorhydrin;fluid;CE
mainbroken;resource-refinining;processing-crafting;filter-charcoal;item;Ch
main;bio-processing-nauvis;bio-processing-wood;wood-charcoal;item;Ch
main;bio-processing-nauvis;bio-processing-wood;wood-pellets;item;Ch
mainbroken;bio-processing-nauvis;bio-processing-wood;pellet-charcoal;item;Ch
mainbroken;petrochem-refining;petrochem-solids;cliff-explosives;item;CL
main;angels-smelting;angels-stone;clay-brick;item;CL
main;petrochem-refining;petrochem-chlorine-fluids;gas-chlorine;fluid;Cl
main;water-treatment;water-treatment-fluid;liquid-coolant;fluid;CL
main;petrochem-refining;petrochem-chlorine-fluids;gas-chlor-methane;fluid;CM
Englishmentals;angels-casting;angels-stone-casting;concrete;item;CO
Englishmentals;angels-casting;angels-stone-casting;concrete-brick;item;CO
Englishmentals;angels-casting;angels-stone-casting;liquid-concrete;fluid;CO
Englishmentals;angels-smelting;angels-cobalt;cobalt-ore;item;Co
Englishmentals;angels-smelting;angels-cobalt;cobalt-oxide;item;Co
Englishmentals;angels-smelting;angels-cobalt;ingot-cobalt;item;Co
Englishmentals;angels-smelting;angels-cobalt;pellet-cobalt;item;Co
Englishmentals;angels-smelting;angels-cobalt;powder-cobalt;item;Co
Englishmentals;angels-smelting;angels-cobalt;processed-cobalt;item;Co
Englishmentals;angels-smelting;angels-cobalt;solid-cobalt-hydroxide;item;Co
Englishmentals;bio-processing-alien;bio-processing-paste;paste-cobalt;item;Co
main;angels-casting;angels-stone-casting;concrete;item;CO
main;angels-casting;angels-stone-casting;concrete-brick;item;CO
main;angels-casting;angels-stone-casting;liquid-concrete;fluid;CO
main;angels-smelting;angels-cobalt;cobalt-ore;item;Co
main;angels-smelting;angels-cobalt;cobalt-oxide;item;Co
main;angels-smelting;angels-cobalt;ingot-cobalt;item;Co
main;angels-smelting;angels-cobalt;pellet-cobalt;item;Co
main;angels-smelting;angels-cobalt;powder-cobalt;item;Co
main;angels-smelting;angels-cobalt;processed-cobalt;item;Co
main;angels-smelting;angels-cobalt;solid-cobalt-hydroxide;item;Co
main;bio-processing-alien;bio-processing-paste;paste-cobalt;item;Co
main;petrochem-refining;petrochem-raw-fluids;crude-oil;fluid;CO
Englishmentals;angels-casting;angels-copper-casting;angels-roll-copper;item;Cp
Englishmentals;angels-casting;angels-copper-casting;angels-wire-coil-copper;item;Cp
Englishmentals;angels-casting;angels-copper-casting;copper-cable;item;Cp
Englishmentals;angels-casting;angels-copper-casting;copper-plate;item;Cp
Englishmentals;angels-casting;angels-copper-casting;liquid-molten-copper;fluid;Cp
Englishmentals;angels-smelting;angels-copper;anode-copper;item;Cp
Englishmentals;angels-smelting;angels-copper;copper-ore;item;Cp
Englishmentals;angels-smelting;angels-copper;ingot-copper;item;Cp
Englishmentals;angels-smelting;angels-copper;pellet-copper;item;Cp
Englishmentals;angels-smelting;angels-copper;powder-copper;item;Cp
Englishmentals;angels-smelting;angels-copper;processed-copper;item;Cp
main;petrochem-refining;petrochem-chlorine-fluids;liquid-perchloric-acid;fluid;CP
Englishmentals;angels-smelting;angels-chrome;chrome-ore;item;Cr
Englishmentals;angels-smelting;angels-chrome;ingot-chrome;item;Cr
Englishmentals;angels-smelting;angels-chrome;pellet-chrome;item;Cr
Englishmentals;angels-smelting;angels-chrome;processed-chrome;item;Cr
Englishmentals;angels-smelting;angels-chrome;solid-chromate;item;Cr
Englishmentals;angels-smelting;angels-chrome;solid-chrome-oxide;item;Cr
Englishmentals;angels-smelting;angels-chrome;solid-dichromate;item;Cr
main;angels-casting;angels-chrome-casting;angels-roll-chrome;item;Cr
main;angels-casting;angels-chrome-casting;angels-plate-chrome;item;Cr
main;angels-casting;angels-chrome-casting;liquid-molten-chrome;fluid;Cr
main;angels-smelting;angels-chrome;chrome-ore;item;Cr
main;angels-smelting;angels-chrome;ingot-chrome;item;Cr
main;angels-smelting;angels-chrome;pellet-chrome;item;Cr
main;angels-smelting;angels-chrome;processed-chrome;item;Cr
main;angels-smelting;angels-chrome;solid-chromate;item;Cr
main;angels-smelting;angels-chrome;solid-chrome-oxide;item;Cr
main;angels-smelting;angels-chrome;solid-dichromate;item;Cr
main;angels-smelting;angels-stone;clay-brick-raw;item;CR
main;resource-refinining;angels-ores;angels-ore4;item;Cr
main;resource-refinining;ore-processing-a;angels-ore4-crushed;item;Cr
main;resource-refinining;ore-processing-b;angels-ore4-chunk;item;Cr
main;resource-refinining;ore-processing-c;angels-ore4-crystal;item;Cr
main;resource-refinining;ore-processing-d;angels-ore4-pure;item;Cr
Englishmentals;angels-casting;angels-alloys-casting;cobalt-steel-alloy;item;CS
Englishmentals;angels-casting;angels-alloys-casting;liquid-molten-cobalt-steel;fluid;CS
main;angels-casting;angels-alloys-casting;cobalt-steel-alloy;item;CS
main;angels-casting;angels-alloys-casting;liquid-molten-cobalt-steel;fluid;CS
main;bio-processing-alien;bio-processing-alien-intermediate;crystal-seed;item;CS
main;petrochem-refining;petrochem-sulfur;solid-calcium-sulfate;item;CS
mainbroken;combat;ammo;cannon-shell;item;Cs
Englishmentals;bio-processing-alien;bio-processing-paste;paste-copper;item;Cu
Englishmentals;resource-refinining;ore-processing-a;angels-ore9-crushed;item;Cu
Englishmentals;resource-refinining;ore-processing-a;angels-ore9-powder;item;Cu
Englishmentals;resource-refinining;ore-processing-b;angels-ore9-dust;item;Cu
Englishmentals;resource-refinining;ore-processing-c;angels-ore9-crystal;item;Cu
Englishmentals;resource-refinining;ore-processing-fluid;angels-ore9-anode-sludge;fluid;Cu
Englishmentals;resource-refinining;ore-processing-fluid;angels-ore9-anode-sludge;fluid;Cu
Englishmentals;resource-refinining;ore-processing-fluid;angels-ore9-sludge;fluid;Cu
Englishmentals;resource-refinining;ore-processing-fluid;angels-ore9-solution;fluid;Cu
Englishmentals;resource-refinining;ore-processing-fluid;liquid-cupric-chloride-solution;fluid;Cu
main;angels-casting;angels-copper-casting;angels-roll-copper;item;Cu
main;angels-casting;angels-copper-casting;angels-wire-coil-copper;item;Cu
main;angels-casting;angels-copper-casting;copper-cable;item;Cu
main;angels-casting;angels-copper-casting;copper-plate;item;Cu
main;angels-casting;angels-copper-casting;liquid-molten-copper;fluid;Cu
main;angels-smelting;angels-copper;anode-copper;item;Cu
main;angels-smelting;angels-copper;copper-ore;item;Cu
main;angels-smelting;angels-copper;ingot-copper;item;Cu
main;angels-smelting;angels-copper;pellet-copper;item;Cu
main;angels-smelting;angels-copper;powder-copper;item;Cu
main;angels-smelting;angels-copper;processed-copper;item;Cu
main;bio-processing-alien;bio-processing-paste;paste-copper;item;Cu
main;resource-refinining;ore-processing-a;angels-ore9-crushed;item;Cu
main;resource-refinining;ore-processing-a;angels-ore9-powder;item;Cu
main;resource-refinining;ore-processing-b;angels-ore9-dust;item;Cu
main;resource-refinining;ore-processing-c;angels-ore9-crystal;item;Cu
main;resource-refinining;ore-processing-fluid;angels-ore9-anode-sludge;fluid;Cu
main;resource-refinining;ore-processing-fluid;angels-ore9-anode-sludge;fluid;Cu
main;resource-refinining;ore-processing-fluid;angels-ore9-sludge;fluid;Cu
main;resource-refinining;ore-processing-fluid;angels-ore9-solution;fluid;Cu
main;resource-refinining;ore-processing-fluid;liquid-cupric-chloride-solution;fluid;Cu
main;resource-refinining;processing-crafting;filter-ceramic-used;item;CU
main;water-treatment;water-treatment-fluid;liquid-coolant-used;fluid;CU
main;resource-refinining;geode-processing-1;geode-cyan;item;Cy
main;resource-refinining;ore-sorting-fluid;crystal-slurry;fluid;CY
main;bio-processing-vegetables;bio-processing-blocks;desert-upgrade;item;D
main;bio-processing-vegetables;bio-processing-vegetables;desert-farm;item;D
main;bio-processing-vegetables;farming-desert-seed;desert-3-seed-dormant;item;d
main;bio-processing-vegetables;farming-desert-seed;desert-4-seed-dormant;item;d
main;bio-processing-vegetables;farming-desert-seed;desert-5-seed-dormant;item;d
main;bio-processing-vegetables;farming-swamp-seed;swamp-3-seed-dormant;item;d
main;bio-processing-vegetables;farming-swamp-seed;swamp-4-seed-dormant;item;d
main;bio-processing-vegetables;farming-swamp-seed;swamp-5-seed-dormant;item;d
main;bio-processing-vegetables;farming-temperate-seed;temperate-3-seed-dormant;item;d
main;bio-processing-vegetables;farming-temperate-seed;temperate-4-seed-dormant;item;d
main;bio-processing-vegetables;farming-temperate-seed;temperate-5-seed-dormant;item;d
main;petrochem-refining;petrochem-basic-fluids;gas-deuterium;fluid;D
main;resource-refinining;geode-processing-1;crystal-dust;item;D
main;intermediate-products;bob-fuel-cells;deuterium-fuel-cell;item;D1
main;intermediate-products;bob-fuel-cells;deuterium-fuel-cell-2;item;D2
main;logistics;terrain;landfill-dry-dirt;item;DD
main;logistics;terrain;landfill-dirt-4;item;Dr
main;intermediate-products;bob-fuel-cells;used-up-deuterium-fuel-cell;item;Dx
main;bobmodules;module-intermediates;effectivity-processor;item;E
main;bobmodules;module-intermediates;effectivity-processor-2;item;E
main;bobmodules;module-intermediates;effectivity-processor-3;item;E
main;petrochem-refining;petrochem-catalysts;angels-electrode;item;E
mainbroken;bobmodules;effectivity-module;effectivity-module;item;E
mainbroken;bobmodules;effectivity-module;effectivity-module-2;item;E
mainbroken;bobmodules;effectivity-module;effectivity-module-3;item;E
mainbroken;bobmodules;effectivity-module;effectivity-module-4;item;E
mainbroken;bobmodules;effectivity-module;effectivity-module-5;item;E
mainbroken;bobmodules;effectivity-module;effectivity-module-6;item;E
mainbroken;bobmodules;effectivity-module;effectivity-module-7;item;E
mainbroken;bobmodules;effectivity-module;effectivity-module-8;item;E
main;bio-processing-alien;bio-processing-alien-intermediate;egg-shell-seed;item;ES
main;petrochem-refining;petrochem-catalysts;angels-electrode-used;item;EU
main;petrochem-refining;petrochem-solids;explosives;item;Ex
mainbroken;combat;ammo;explosive-cannon-shell;item;Ex
mainbroken;intermediate-products;bob-boards;fibreglass-board;item;F
main;bio-processing-alien;bio-fish;liquid-fish-oil;fluid;F
main;bio-processing-nauvis;bio-wood;solid-fertilizer;item;F
main;resource-refinining;processing-crafting;filter-frame;item;F
main;petrochem-refining;petrochem-sulfer-fluids;liquid-hydrofluoric-acid;fluid;FA
main;angels-casting;angels-iron-casting;angels-roll-iron;item;Fe
main;angels-casting;angels-iron-casting;iron-plate;item;Fe
main;angels-casting;angels-iron-casting;iron-stick;item;Fe
main;angels-casting;angels-iron-casting;liquid-molten-iron;fluid;Fe
main;angels-smelting;angels-iron;ingot-iron;item;Fe
main;angels-smelting;angels-iron;iron-ore;item;Fe
main;angels-smelting;angels-iron;pellet-iron;item;Fe
main;angels-smelting;angels-iron;powder-iron;item;Fe
main;angels-smelting;angels-iron;processed-iron;item;Fe
main;angels-smelting;angels-iron;solid-iron-hydroxide;item;Fe
main;bio-processing-alien;bio-processing-paste;paste-iron;item;Fe
main;bio-processing-vegetables;bio-processing-vegetables;crop-farm;item;Fe
main;resource-refinining;ore-processing-a;angels-ore8-crushed;item;Fe
main;resource-refinining;ore-processing-a;angels-ore8-powder;item;Fe
main;resource-refinining;ore-processing-b;angels-ore8-dust;item;Fe
main;resource-refinining;ore-processing-c;angels-ore8-crystal;item;Fe
main;resource-refinining;ore-processing-fluid;angels-ore8-anode-sludge;fluid;Fe
main;resource-refinining;ore-processing-fluid;angels-ore8-slime;fluid;Fe
main;resource-refinining;ore-processing-fluid;angels-ore8-sludge;fluid;Fe
main;resource-refinining;ore-processing-fluid;angels-ore8-solution;fluid;Fe
main;resource-refinining;ore-processing-fluid;liquid-ferric-chloride-solution;fluid;Fe
main;petrochem-refining;petrochem-fuel;solid-fuel;item;Fl
main;petrochem-refining;petrochem-sulfur;fluorite-ore;item;Fl
main;bio-processing-alien;bio-fish;fish-pulp;item;FP
main;bio-processing-alien;bio-fish;liquid-polluted-fish-atmosphere;fluid;FP
main;petrochem-refining;petrochem-carbon-fluids;liquid-fuel-oil;fluid;FS
main;bio-processing-alien;bio-fish;liquid-fish-atmosphere;fluid;FW
main;water-treatment;water-cleaning-fluid;water-greenyellow-waste;fluid;FW
Englishmentals;angels-casting;angels-gold-casting;angels-roll-gold;item;G
Englishmentals;angels-casting;angels-gold-casting;angels-wire-coil-gold;item;G
Englishmentals;angels-casting;angels-gold-casting;gilded-copper-cable;item;G
Englishmentals;angels-casting;angels-gold-casting;gold-plate;item;G
Englishmentals;angels-casting;angels-gold-casting;liquid-molten-gold;fluid;G
Englishmentals;angels-smelting;angels-gold;cathode-gold;item;G
Englishmentals;angels-smelting;angels-gold;gold-ore;item;G
Englishmentals;angels-smelting;angels-gold;ingot-gold;item;G
Englishmentals;angels-smelting;angels-gold;liquid-chlorauric-acid;fluid;G
Englishmentals;angels-smelting;angels-gold;pellet-gold;item;G
Englishmentals;angels-smelting;angels-gold;powder-gold;item;G
Englishmentals;angels-smelting;angels-gold;processed-gold;item;G
Englishmentalsbroken;angels-smelting;angels-gold;sodium-gold-cyanide;item;G
main;bio-processing-alien;bio-puffer-2;bio-puffer-1;item;G
main;bio-processing-alien;bio-puffer-egg;bio-puffer-egg-1;item;G
main;bobs-gems;bio-biter-processing-crystal-full;crystal-full-green;item;G
main;bobs-gems;bio-biter-processing-crystal-full;crystal-full-green-cut;item;G
main;bobs-gems;bio-biter-processing-crystal-shard;crystal-shard-green;item;G
main;bobs-gems;bio-biter-processing-crystal-shard;crystal-shard-green-cut;item;G
main;bobs-gems;bio-biter-processing-crystal-splinter;crystal-splinter-green;item;G
main;bobs-gems;bio-biter-processing-crystal-splinter;crystal-splinter-green-cut;item;G
Englishmentalsbroken;sct-science;sct-bio-science-pack;sct-bio-science-pack;item;G2
mainbroken;sct-science;sct-bio-science-pack;sct-bio-science-pack;item;G2
main;petrochem-refining;petrochem-sulfer-fluids;gas-acid;fluid;GA
Englishmentals;angels-casting;angels-glass-casting;angels-coil-glass-fiber;item;Gl
Englishmentals;angels-casting;angels-glass-casting;glass;item;Gl
Englishmentals;angels-casting;angels-glass-casting;liquid-molten-glass;fluid;Gl
Englishmentalsbroken;angels-smelting;angels-glass;glass-mixture;item;Gl
main;angels-casting;angels-glass-casting;angels-coil-glass-fiber;item;Gl
main;angels-casting;angels-glass-casting;glass;item;Gl
main;angels-casting;angels-glass-casting;liquid-molten-glass;fluid;Gl
main;angels-smelting;angels-glass;solid-glass-mixture;item;Gl
Englishmentalsbroken;sct-science;sct-science-pack-2;logistic-science-pack;item;Gn
mainbroken;sct-science;sct-science-pack-2;logistic-science-pack;item;Gn
main;bio-processing-alien;bio-processing-alien-large;alien-artifact-green;item;Gn
main;bio-processing-alien;bio-processing-alien-pre;alien-pre-artifact-green;item;Gn
main;bio-processing-alien;bio-processing-alien-small;small-alien-artifact-green;item;Gn
main;bio-processing-nauvis;bio-liquor;liquid-green-liquor;fluid;Gn
main;bio-processing-nauvis;bio-processing-green;algae-green;item;Gn
main;bio-processing-nauvis;bio-processing-green;paste-cellulose;item;Gn
main;bio-processing-nauvis;bio-processing-wood;cellulose-fiber;item;Gn
main;intermediate-products;bob-electronic-boards;cp-electronic-circuit-board;item;Gn
main;intermediate-products;bob-electronic-boards;electronic-circuit;item;Gn
main;petrochem-refining;petrochem-catalysts;catalyst-metal-green;item;Gn
main;logistics;terrain;landfill-grass-1;item;Gr
main;petrochem-refining;petrochem-raw-fluids;gas-raw-1;fluid;GR
Englishmentalsbroken;sct-science;sct-sciencepack-mil;military-science-pack;item;Gy
mainbroken;sct-science;sct-sciencepack-mil;military-science-pack;item;Gy
main;bobs-gems;bio-biter-processing-crystal-full;crystal-full-harmonic;item;H
main;bobs-gems;bio-biter-processing-crystal-shard;crystal-shard-harmonic;item;H
main;bobs-gems;bio-biter-processing-crystal-splinter;crystal-splinter-harmonic;item;H
main;petrochem-refining;petrochem-basic-fluids;gas-hydrogen;fluid;H
main;resource-refinining;processing-crafting;catalysator-orange;item;H
Englishmentals;angels-casting;angels-stone-casting;hazard-concrete;item;HC
main;angels-casting;angels-stone-casting;hazard-concrete;item;HC
main;petrochem-refining;petrochem-chlorine-fluids;gas-hydrogen-chloride;fluid;HC
main;petrochem-refining;petrochem-sulfer-fluids;gas-hydrogen-fluoride;fluid;HF
main;petrochem-refining;petrochem-sulfer-fluids;gas-hydrogen-sulfide;fluid;HS
Englishmentals;bio-processing-alien;bio-processing-paste;paste-iron;item;I
Englishmentals;bio-processing-vegetables;bio-processing-vegetables;crop-farm;item;I
Englishmentals;resource-refinining;ore-processing-a;angels-ore8-crushed;item;I
Englishmentals;resource-refinining;ore-processing-a;angels-ore8-powder;item;I
Englishmentals;resource-refinining;ore-processing-b;angels-ore8-dust;item;I
Englishmentals;resource-refinining;ore-processing-c;angels-ore8-crystal;item;I
Englishmentals;resource-refinining;ore-processing-fluid;angels-ore8-anode-sludge;fluid;I
Englishmentals;resource-refinining;ore-processing-fluid;angels-ore8-slime;fluid;I
Englishmentals;resource-refinining;ore-processing-fluid;angels-ore8-sludge;fluid;I
Englishmentals;resource-refinining;ore-processing-fluid;angels-ore8-solution;fluid;I
Englishmentals;resource-refinining;ore-processing-fluid;liquid-ferric-chloride-solution;fluid;I
Englishmentals;angels-casting;angels-alloys-casting;invar-alloy;item;In
Englishmentals;angels-casting;angels-alloys-casting;liquid-molten-invar;fluid;In
main;angels-casting;angels-alloys-casting;invar-alloy;item;In
main;angels-casting;angels-alloys-casting;liquid-molten-invar;fluid;In
Englishmentals;angels-casting;angels-iron-casting;angels-roll-iron;item;Ir
Englishmentals;angels-casting;angels-iron-casting;iron-plate;item;Ir
Englishmentals;angels-casting;angels-iron-casting;iron-stick;item;Ir
Englishmentals;angels-casting;angels-iron-casting;liquid-molten-iron;fluid;Ir
Englishmentals;angels-smelting;angels-iron;ingot-iron;item;Ir
Englishmentals;angels-smelting;angels-iron;iron-ore;item;Ir
Englishmentals;angels-smelting;angels-iron;pellet-iron;item;Ir
Englishmentals;angels-smelting;angels-iron;powder-iron;item;Ir
Englishmentals;angels-smelting;angels-iron;processed-iron;item;Ir
Englishmentals;angels-smelting;angels-iron;solid-iron-hydroxide;item;Ir
main;resource-refinining;angels-ores;angels-ore2;item;Ji
main;resource-refinining;ore-processing-a;angels-ore2-crushed;item;Ji
main;resource-refinining;ore-processing-b;angels-ore2-chunk;item;Ji
main;resource-refinining;ore-processing-c;angels-ore2-crystal;item;Ji
main;resource-refinining;ore-processing-d;angels-ore2-pure;item;Ji
Englishmentals;angels-casting;angels-lead-casting;angels-roll-lead;item;L
Englishmentals;angels-casting;angels-lead-casting;lead-plate;item;L
Englishmentals;angels-casting;angels-lead-casting;liquid-molten-lead;fluid;L
Englishmentals;angels-smelting;angels-lead;anode-lead;item;L
Englishmentals;angels-smelting;angels-lead;ingot-lead;item;L
Englishmentals;angels-smelting;angels-lead;lead-ore;item;L
Englishmentals;angels-smelting;angels-lead;lead-oxide;item;L
Englishmentals;angels-smelting;angels-lead;liquid-hexafluorosilicic-acid;fluid;L
Englishmentals;angels-smelting;angels-lead;pellet-lead;item;L
Englishmentals;angels-smelting;angels-lead;processed-lead;item;L
main;bio-processing-vegetables;bio-processor-nutrient;solid-leafs;item;L
main;intermediate-products;bob-robot-parts;robot-brain-logistic;item;L1
main;intermediate-products;bob-robot-parts;robot-brain-logistic-2;item;L2
main;intermediate-products;bob-robot-parts;robot-brain-logistic-3;item;L3
main;intermediate-products;bob-robot-parts;robot-brain-logistic-4;item;L4
main;logistics;terrain;landfill;item;LF
main;petrochem-refining;petrochem-carbon-fluids;liquid-fuel;fluid;LF
main;resource-refinining;geode-processing-1;geode-lightgreen;item;LG
Englishmentals;angels-smelting;angels-alloys;lithium;item;Li
Englishmentals;angels-smelting;angels-alloys;lithium-cobalt-oxide;item;Li
Englishmentals;angels-smelting;angels-alloys;lithium-perchlorate;item;Li
main;angels-smelting;angels-alloys;lithium;item;Li
main;angels-smelting;angels-alloys;lithium-cobalt-oxide;item;Li
main;angels-smelting;angels-alloys;lithium-perchlorate;item;Li
main;intermediate-products;bob-intermediates;lithium-ion-battery;item;Li
main;petrochem-refining;petrochem-catalysts;filter-lime;item;Li
main;water-treatment;water-salination;solid-lithium;item;Li
main;water-treatment;water-salination;solid-limestone;item;Lm
main;petrochem-refining;petrochem-carbon-fluids;lubricant;fluid;Lu
main;petrochem-refining;petrochem-catalysts;filter-lime-used;item;Lu
main;bio-processing-alien;bio-biter;biter-medium;item;M
main;bio-processing-alien;bio-biter;biter-medium-egg;item;M
main;bio-processing-alien;bio-biter;biter-queen-medium;item;M
main;bobmodules;module-intermediates;module-case;item;M
main;bobmodules;module-intermediates;module-circuit-board;item;M
main;bobmodules;module-intermediates;module-contact;item;M
main;bobmodules;module-intermediates;module-processor-board;item;M
main;bobmodules;module-intermediates;module-processor-board-2;item;M
main;bobmodules;module-intermediates;module-processor-board-3;item;M
main;resource-refinining;processing-crafting;catalysator-brown;item;M
mainbroken;sct-science;sct-sciencepack-mil;sct-mil-circuit1;item;MB
main;intermediate-products;mech-parts;mech-brain;item;MB
main;petrochem-refining;petrochem-carbon-fluids;gas-ethane;fluid;ME
main;angels-smelting;angels-manganese;cathode-manganese;item;Mn
main;angels-smelting;angels-manganese;ingot-manganese;item;Mn
main;angels-smelting;angels-manganese;manganese-ore;item;Mn
main;angels-smelting;angels-manganese;pellet-manganese;item;Mn
main;angels-smelting;angels-manganese;processed-manganese;item;Mn
main;angels-smelting;angels-manganese;solid-manganese-oxide;item;Mn
main;petrochem-refining;petrochem-carbon-fluids;liquid-mineral-oil;fluid;MO
mainbroken;sct-science;sct-sciencepack-mil;sct-mil-plating;item;MP
main;petrochem-refining;petrochem-raw-fluids;liquid-multi-phase-oil;fluid;MP
main;intermediate-products;bob-fuel-cells;empty-nuclear-fuel-cell;item;MT
main;petrochem-refining;petrochem-catalysts;catalyst-metal-carrier;item;MT
main;water-treatment;water-treatment-fluid;water-mineralized;fluid;MW
main;bio-processing-vegetables;bio-processor-nutrient;solid-nuts;item;N
main;petrochem-refining;petrochem-nitrogen-fluids;gas-nitrogen;fluid;N
main;water-treatment;water-cleaning-fluid;water-red-waste;fluid;N
main;petrochem-refining;petrochem-nitrogen;solid-ammonium-nitrate;item;N1
main;petrochem-refining;petrochem-nitrogen-fluids;gas-nitrogen-monoxide;fluid;N1
main;petrochem-refining;petrochem-nitrogen;solid-ammonium-perchlorate;item;N2
main;petrochem-refining;petrochem-nitrogen-fluids;gas-melamine;fluid;N2
main;petrochem-refining;petrochem-nitrogen-fluids;gas-monochloramine;fluid;N3
main;petrochem-refining;petrochem-nitrogen-fluids;gas-methylamine;fluid;N4
main;petrochem-refining;petrochem-nitrogen-fluids;gas-dimethylamine;fluid;N5
main;petrochem-refining;petrochem-nitrogen-fluids;gas-dimethylhydrazine;fluid;N6
main;petrochem-refining;petrochem-nitrogen-fluids;liquid-nitric-acid;fluid;NA
main;petrochem-refining;petrochem-sodium;solid-sodium;item;Na
main;petrochem-refining;petrochem-nitrogen-fluids;gas-ammonium-chloride;fluid;NC
main;petrochem-refining;petrochem-nitrogen-fluids;gas-nitrogen-dioxide;fluid;ND
main;petrochem-refining;petrochem-nitrogen-fluids;gas-hydrazine;fluid;NH
main;angels-smelting;angels-nickel;cathode-nickel;item;Ni
main;angels-smelting;angels-nickel;ingot-nickel;item;Ni
main;angels-smelting;angels-nickel;nickel-ore;item;Ni
main;angels-smelting;angels-nickel;pellet-nickel;item;Ni
main;angels-smelting;angels-nickel;powder-nickel;item;Ni
main;angels-smelting;angels-nickel;processed-nickel;item;Ni
main;angels-smelting;angels-nickel;solid-nickel-carbonyl;item;Ni
main;bio-processing-vegetables;bio-processor-nutrient;liquid-nutrient-pulp;fluid;NP
main;petrochem-refining;petrochem-raw-fluids;liquid-ngl;fluid;Np
Englishmentals;angels-casting;angels-alloys-casting;liquid-molten-nitinol;fluid;NT
Englishmentals;angels-casting;angels-alloys-casting;nitinol-alloy;item;NT
main;angels-casting;angels-alloys-casting;liquid-molten-nitinol;fluid;NT
main;angels-casting;angels-alloys-casting;nitinol-alloy;item;NT
main;petrochem-refining;petrochem-nitrogen-fluids;gas-dinitrogen-tetroxide;fluid;NT
main;petrochem-refining;petrochem-basic-fluids;gas-oxygen;fluid;O
main;bio-processing-alien;bio-processing-alien-large;alien-artifact-orange;item;Or
main;bio-processing-alien;bio-processing-alien-pre;alien-pre-artifact-orange;item;Or
main;bio-processing-alien;bio-processing-alien-small;small-alien-artifact-orange;item;Or
main;petrochem-refining;petrochem-carbon-oil-feed;solid-oil-residual;item;OR
main;bio-processing-nauvis;bio-arboretum-swamp;bio-plastic;item;P
main;bio-processing-nauvis;bio-paper;solid-paper;item;P
main;bio-processing-vegetables;bio-processor-nutrient;solid-pips;item;P
main;bobmodules;module-intermediates;productivity-processor;item;P
main;bobmodules;module-intermediates;productivity-processor-2;item;P
main;bobmodules;module-intermediates;productivity-processor-3;item;P
main;intermediate-products;bob-boards;phenolic-board;item;P
main;water-treatment;water-treatment-fluid;water-purified;fluid;P
mainbroken;bobmodules;productivity-module;productivity-module;item;P
mainbroken;bobmodules;productivity-module;productivity-module-2;item;P
mainbroken;bobmodules;productivity-module;productivity-module-3;item;P
mainbroken;bobmodules;productivity-module;productivity-module-4;item;P
mainbroken;bobmodules;productivity-module;productivity-module-5;item;P
mainbroken;bobmodules;productivity-module;productivity-module-6;item;P
mainbroken;bobmodules;productivity-module;productivity-module-7;item;P
mainbroken;bobmodules;productivity-module;productivity-module-8;item;P
mainbroken;combat;ammo;piercing-rounds-magazine;item;P
main;petrochem-refining;petrochem-carbon-fluids;gas-propene;fluid;P1
main;petrochem-refining;petrochem-carbon-fluids;gas-methanol;fluid;P2
main;petrochem-refining;petrochem-carbon-fluids;gas-ethylene;fluid;P3
main;petrochem-refining;petrochem-carbon-fluids;gas-benzene;fluid;P4
main;petrochem-refining;petrochem-carbon-fluids;gas-butadiene;fluid;P5
main;petrochem-refining;petrochem-carbon-fluids;liquid-ethylbenzene;fluid;P6
main;petrochem-refining;petrochem-carbon-fluids;gas-acetone;fluid;P7
main;petrochem-refining;petrochem-carbon-fluids;liquid-bisphenol-a;fluid;P9
main;bio-processing-alien;bio-puffer-1;gas-puffer-atmosphere;fluid;PA
main;angels-casting;angels-lead-casting;angels-roll-lead;item;Pb
main;angels-casting;angels-lead-casting;lead-plate;item;Pb
main;angels-casting;angels-lead-casting;liquid-molten-lead;fluid;Pb
main;angels-smelting;angels-lead;anode-lead;item;Pb
main;angels-smelting;angels-lead;ingot-lead;item;Pb
main;angels-smelting;angels-lead;lead-ore;item;Pb
main;angels-smelting;angels-lead;lead-oxide;item;Pb
main;angels-smelting;angels-lead;liquid-hexafluorosilicic-acid;fluid;Pb
main;angels-smelting;angels-lead;pellet-lead;item;Pb
main;angels-smelting;angels-lead;processed-lead;item;Pb
main;petrochem-refining;petrochem-carbon-fluids;gas-butane;fluid;PB
main;bio-processing-alien;bio-processing-alien-intermediate;petri-dish;item;PD
main;petrochem-refining;petrochem-carbon-fluids;gas-formaldehyde;fluid;PF
main;petrochem-refining;petrochem-carbon-fluids;liquid-phenol;fluid;Ph
Englishmentalsbroken;sct-science;sct-advanced-logistic-science-pack;advanced-logistic-science-pack;item;Pi
mainbroken;sct-science;sct-advanced-logistic-science-pack;advanced-logistic-science-pack;item;Pi
main;bio-processing-nauvis;bio-liquor;liquid-pulping-liquor;fluid;Pl
main;petrochem-refining;petrochem-solids-fluids;liquid-plastic;fluid;Pl
main;petrochem-refining;petrochem-carbon-fluids;gas-methane;fluid;PM
main;petrochem-refining;petrochem-carbon-fluids;liquid-naphtha;fluid;PN
Englishmentalsbroken;sct-science;sct-sciencepack-prod;production-science-pack;item;Pp
mainbroken;sct-science;sct-sciencepack-prod;production-science-pack;item;Pp
main;bio-processing-alien;bio-processing-alien-large;alien-artifact-purple;item;Pp
main;bio-processing-alien;bio-processing-alien-pre;alien-pre-artifact-purple;item;Pp
main;bio-processing-alien;bio-processing-alien-small;small-alien-artifact-purple;item;Pp
main;petrochem-refining;petrochem-carbon-fluids;liquid-polyethylene;fluid;PP
main;resource-refinining;geode-processing-1;geode-purple;item;Pp
Englishmentals;angels-casting;angels-platinum-casting;angels-roll-platinum;item;Pt
Englishmentals;angels-casting;angels-platinum-casting;angels-wire-coil-platinum;item;Pt
Englishmentals;angels-casting;angels-platinum-casting;angels-wire-platinum;item;Pt
Englishmentals;angels-casting;angels-platinum-casting;liquid-molten-platinum;fluid;Pt
Englishmentalsbroken;angels-casting;angels-platinum-casting;platinum-plate;item;Pt
main;angels-casting;angels-platinum-casting;angels-roll-platinum;item;Pt
main;angels-casting;angels-platinum-casting;angels-wire-coil-platinum;item;Pt
main;angels-casting;angels-platinum-casting;angels-wire-platinum;item;Pt
main;angels-casting;angels-platinum-casting;liquid-molten-platinum;fluid;Pt
main;angels-casting;angels-platinum-casting;angels-plate-platinum;item;Pt
main;angels-smelting;angels-platinum;ingot-platinum;item;Pt
main;angels-smelting;angels-platinum;liquid-hexachloroplatinic-acid;fluid;Pt
main;angels-smelting;angels-platinum;pellet-platinum;item;Pt
main;angels-smelting;angels-platinum;platinum-ore;item;Pt
main;angels-smelting;angels-platinum;processed-platinum;item;Pt
main;angels-smelting;angels-platinum;solid-ammonium-chloroplatinate;item;Pt
main;intermediate-products;bob-fuel-cells;plutonium-fuel-cell;item;Pu
main;intermediate-products;bob-fuel-cells;thorium-plutonium-fuel-cell;item;Pu
main;intermediate-products;bob-nuclear;plutonium-239;item;Pu
main;bio-processing-alien;bio-puffer-3;bio-puffer-2;item;R
main;bio-processing-alien;bio-puffer-egg;bio-puffer-egg-2;item;R
main;bobs-gems;bio-biter-processing-crystal-full;crystal-full-red;item;R
main;bobs-gems;bio-biter-processing-crystal-full;crystal-full-red-cut;item;R
main;bobs-gems;bio-biter-processing-crystal-shard;crystal-shard-red;item;R
main;bobs-gems;bio-biter-processing-crystal-shard;crystal-shard-red-cut;item;R
main;bobs-gems;bio-biter-processing-crystal-splinter;crystal-splinter-red;item;R
main;bobs-gems;bio-biter-processing-crystal-splinter;crystal-splinter-red-cut;item;R
main;bio-processing-nauvis;bio-arboretum-swamp;bio-rubber;item;Rb
Englishmentals;angels-casting;angels-stone-casting;refined-concrete;item;RC
Englishmentals;angels-casting;angels-stone-casting;reinforced-concrete-brick;item;RC
main;angels-casting;angels-stone-casting;refined-concrete;item;RC
main;angels-casting;angels-stone-casting;reinforced-concrete-brick;item;RC
main;logistics;terrain;landfill-red-desert-1;item;Rd
Englishmentalsbroken;sct-science;sct-science-pack-1;automation-science-pack;item;Re
mainbroken;sct-science;sct-science-pack-1;automation-science-pack;item;Re
main;bio-processing-alien;bio-processing-alien-large;alien-artifact-red;item;Re
main;bio-processing-alien;bio-processing-alien-pre;alien-pre-artifact-red;item;Re
main;bio-processing-alien;bio-processing-alien-small;small-alien-artifact-red;item;Re
main;bio-processing-nauvis;bio-arboretum-swamp;bio-resin;item;Re
main;bio-processing-nauvis;bio-processing-red;algae-red;item;Re
main;bio-processing-nauvis;bio-processing-red;red-cellulose-fiber;item;Re
main;bio-processing-nauvis;bio-processing-red;solid-calcium-carbonate;item;Re
main;intermediate-products;bob-electronic-boards;advanced-circuit;item;Re
main;intermediate-products;bob-electronic-boards;circuit-board;item;Re
main;intermediate-products;bob-electronic-boards;cp-advanced-circuit-board;item;Re
main;petrochem-refining;petrochem-catalysts;catalyst-metal-red;item;Re
main;petrochem-refining;petrochem-solids;resin;item;Re
main;petrochem-refining;petrochem-solids-fluids;liquid-resin;fluid;Re
main;petrochem-refining;petrochem-solids-fluids;liquid-rubber;fluid;Re
main;resource-refinining;geode-processing-1;geode-red;item;Re
main;bio-processing-alien;bio-fish;liquid-raw-fish-oil;fluid;RF
main;petrochem-refining;petrochem-raw-fluids;gas-residual;fluid;RG
Englishmentals;angels-casting;angels-stone-casting;refined-hazard-concrete;item;RH
main;angels-casting;angels-stone-casting;refined-hazard-concrete;item;RH
main;bio-processing-alien;bio-fish;bio-raw-meat;item;RM
main;resource-refinining;angels-ores;angels-ore5;item;Ru
main;resource-refinining;ore-processing-a;angels-ore5-crushed;item;Ru
main;resource-refinining;ore-processing-b;angels-ore5-chunk;item;Ru
main;resource-refinining;ore-processing-c;angels-ore5-crystal;item;Ru
main;resource-refinining;ore-processing-d;angels-ore5-pure;item;Ru
main;bio-processing-vegetables;bio-processor-press-vegetables;liquid-raw-vegetable-oil;fluid;RV
main;bio-processing-alien;bio-biter;biter-queen-small;item;S
main;bio-processing-alien;bio-biter;biter-small;item;S
main;bio-processing-alien;bio-biter;biter-small-egg;item;S
main;bio-processing-nauvis;bio-wood;solid-soil;item;S
main;bio-processing-vegetables;bio-processing-blocks;swamp-upgrade;item;S
main;bio-processing-vegetables;bio-processing-vegetables;swamp-farm;item;S
main;bobmodules;module-intermediates;speed-processor;item;S
main;bobmodules;module-intermediates;speed-processor-2;item;S
main;bobmodules;module-intermediates;speed-processor-3;item;S
main;petrochem-refining;petrochem-sulfur;sulfur;item;S
main;water-treatment;water-cleaning-fluid;water-yellow-waste;fluid;S
mainbroken;bobmodules;speed-module;speed-module;item;S
mainbroken;bobmodules;speed-module;speed-module-2;item;S
mainbroken;bobmodules;speed-module;speed-module-3;item;S
mainbroken;bobmodules;speed-module;speed-module-4;item;S
mainbroken;bobmodules;speed-module;speed-module-5;item;S
mainbroken;bobmodules;speed-module;speed-module-6;item;S
mainbroken;bobmodules;speed-module;speed-module-7;item;S
mainbroken;bobmodules;speed-module;speed-module-8;item;S
main;logistics;terrain;landfill-sand-3;item;Sa
main;petrochem-refining;petrochem-sulfer-fluids;liquid-sulfuric-acid;fluid;SA
main;resource-refinining;angels-ores;angels-ore1;item;Sa
main;resource-refinining;ore-processing-a;angels-ore1-crushed;item;Sa
main;resource-refinining;ore-processing-b;angels-ore1-chunk;item;Sa
main;resource-refinining;ore-processing-c;angels-ore1-crystal;item;Sa
main;resource-refinining;ore-processing-d;angels-ore1-pure;item;Sa
main;water-treatment;water-salination;solid-salt;item;Sa
main;water-treatment;water-salination;solid-sand;item;Sa
main;water-treatment;water-treatment-fluid;water-saline;fluid;Sa
main;bio-processing-alien;bio-processing-alien-intermediate;substrate-dish;item;SB
Englishmentals;angels-casting;angels-silicon-casting;angels-mono-silicon;item;Sc
Englishmentals;angels-casting;angels-silicon-casting;angels-mono-silicon-seed;item;Sc
Englishmentals;angels-casting;angels-silicon-casting;angels-quartz-crucible;item;Sc
Englishmentals;angels-casting;angels-silicon-casting;liquid-molten-silicon;fluid;Sc
Englishmentals;angels-casting;angels-silicon-casting;silicon-carbide;item;Sc
Englishmentals;angels-casting;angels-silicon-casting;silicon-nitride;item;Sc
Englishmentals;angels-casting;angels-silicon-casting;silicon-wafer;item;Sc
Englishmentals;angels-casting;angels-solder-casting;angels-roll-solder;item;Sd
Englishmentals;angels-casting;angels-solder-casting;liquid-molten-solder;fluid;Sd
Englishmentalsbroken;angels-casting;angels-solder-casting;solder-plate;item;Sd
main;angels-casting;angels-solder-casting;angels-roll-solder;item;Sd
main;angels-casting;angels-solder-casting;liquid-molten-solder;fluid;Sd
main;angels-casting;angels-solder-casting;solder;item;Sd
main;bio-processing-alien;bio-processing-alien-intermediate;seeded-dish;item;SD
main;petrochem-refining;petrochem-sulfer-fluids;gas-sulfur-dioxide;fluid;SD
main;petrochem-refining;petrochem-sulfer-fluids;gas-enriched-hydrogen-sulfide;fluid;SE
main;petrochem-refining;petrochem-carbon-fluids;gas-synthesis;fluid;SG
main;resource-refinining;ore-sorting-fluid;mineral-sludge;fluid;Sg
main;angels-casting;angels-silicon-casting;angels-mono-silicon;item;Si
main;angels-casting;angels-silicon-casting;angels-mono-silicon-seed;item;Si
main;angels-casting;angels-silicon-casting;angels-quartz-crucible;item;Si
main;angels-casting;angels-silicon-casting;liquid-molten-silicon;fluid;Si
main;angels-casting;angels-silicon-casting;silicon-carbide;item;Si
main;angels-casting;angels-silicon-casting;silicon-nitride;item;Si
main;angels-casting;angels-silicon-casting;silicon-wafer;item;Si
main;angels-smelting;angels-silicon;gas-silane;fluid;Si
main;angels-smelting;angels-silicon;ingot-silicon;item;Si
main;angels-smelting;angels-silicon;liquid-trichlorosilane;fluid;Si
main;angels-smelting;angels-silicon;pellet-silica;item;Si
main;angels-smelting;angels-silicon;processed-silica;item;Si
main;angels-smelting;angels-silicon;quartz;item;Si
main;angels-smelting;angels-silicon;silicon-powder;item;Si
main;petrochem-refining;petrochem-basic-fluids;steam;fluid;Sm
main;angels-casting;angels-tin-casting;angels-roll-tin;item;Sn
main;angels-casting;angels-tin-casting;angels-wire-coil-tin;item;Sn
main;angels-casting;angels-tin-casting;liquid-molten-tin;fluid;Sn
main;angels-casting;angels-tin-casting;tin-plate;item;Sn
main;angels-casting;angels-tin-casting;tinned-copper-cable;item;Sn
main;angels-smelting;angels-tin;ingot-tin;item;Sn
main;angels-smelting;angels-tin;pellet-tin;item;Sn
main;angels-smelting;angels-tin;processed-tin;item;Sn
main;angels-smelting;angels-tin;tin-ore;item;Sn
Englishmentalsbroken;sct-science;sct-sciencepack-space;space-science-pack;item;Sp
mainbroken;sct-science;sct-sciencepack-space;space-science-pack;item;Sp
Englishmentals;angels-casting;angels-steel-casting;angels-roll-steel;item;St
Englishmentals;angels-casting;angels-steel-casting;liquid-molten-steel;fluid;St
Englishmentals;angels-casting;angels-steel-casting;steel-plate;item;St
Englishmentals;angels-smelting;angels-iron;ingot-steel;item;St
main;angels-casting;angels-steel-casting;angels-roll-steel;item;St
main;angels-casting;angels-steel-casting;liquid-molten-steel;fluid;St
main;angels-casting;angels-steel-casting;steel-plate;item;St
main;angels-smelting;angels-iron;ingot-steel;item;St
main;angels-smelting;angels-stone;stone-brick;item;St
main;petrochem-refining;petrochem-carbon-fluids;liquid-styrene;fluid;St
main;resource-refinining;angels-ores;angels-ore3;item;St
main;resource-refinining;ore-processing-a;angels-ore3-crushed;item;St
main;resource-refinining;ore-processing-b;angels-ore3-chunk;item;St
main;resource-refinining;ore-processing-c;angels-ore3-crystal;item;St
main;resource-refinining;ore-processing-d;angels-ore3-pure;item;St
Englishmentals;angels-casting;angels-silver-casting;angels-roll-silver;item;Sv
Englishmentals;angels-casting;angels-silver-casting;angels-wire-coil-silver;item;Sv
Englishmentals;angels-casting;angels-silver-casting;angels-wire-silver;item;Sv
Englishmentals;angels-casting;angels-silver-casting;liquid-molten-silver;fluid;Sv
Englishmentals;angels-casting;angels-silver-casting;silver-plate;item;Sv
Englishmentals;angels-smelting;angels-silver;cathode-silver;item;Sv
Englishmentals;angels-smelting;angels-silver;ingot-silver;item;Sv
Englishmentals;angels-smelting;angels-silver;pellet-silver;item;Sv
Englishmentals;angels-smelting;angels-silver;processed-silver;item;Sv
Englishmentals;angels-smelting;angels-silver;silver-nitrate;item;Sv
Englishmentals;angels-smelting;angels-silver;silver-ore;item;Sv
Englishmentals;angels-smelting;angels-silver;silver-oxide;item;Sv
Englishmentals;angels-smelting;angels-silver;solid-sodium-silver-cyanide;item;Sv
main;resource-refinining;ore-sorting-fluid;slag-slurry;fluid;Sy
main;intermediate-products;bob-intermediates;silver-zinc-battery;item;SZ
mainbroken;sct-science;sct-sciencepack-hightech;sct-htech-thermalstore;item;T
main;bio-processing-vegetables;bio-processing-blocks;temperate-upgrade;item;T
main;bio-processing-vegetables;bio-processing-vegetables;temperate-farm;item;T
mainbroken;sct-science;sct-sciencepack-hightech;sct-htech-thermalstore-heated;item;TH
main;intermediate-products;bob-fuel-cells;thorium-fuel-cell;item;Th
main;intermediate-products;bob-nuclear;thorium-232;item;Th
main;resource-refinining;angels-ores;thorium-ore;item;Th
main;angels-casting;angels-aluminium-casting;angels-roll-titanium;item;Ti
main;angels-casting;angels-titanium-casting;liquid-molten-titanium;fluid;Ti
main;angels-casting;angels-titanium-casting;titanium-plate;item;Ti
main;angels-smelting;angels-titanium;ingot-titanium;item;Ti
main;angels-smelting;angels-titanium;liquid-titanium-tetrachloride;fluid;Ti
main;angels-smelting;angels-titanium;pellet-titanium;item;Ti
main;angels-smelting;angels-titanium;powder-titanium;item;Ti
main;angels-smelting;angels-titanium;processed-titanium;item;Ti
main;angels-smelting;angels-titanium;rutile-ore;item;Ti
main;angels-smelting;angels-titanium;sponge-titanium;item;Ti
main;bio-processing-alien;bio-processing-paste;paste-titanium;item;Ti
Englishmentals;angels-casting;angels-tin-casting;angels-roll-tin;item;Tn
Englishmentals;angels-casting;angels-tin-casting;angels-wire-coil-tin;item;Tn
Englishmentals;angels-casting;angels-tin-casting;liquid-molten-tin;fluid;Tn
Englishmentals;angels-casting;angels-tin-casting;tin-plate;item;Tn
Englishmentals;angels-casting;angels-tin-casting;tinned-copper-cable;item;Tn
Englishmentals;angels-smelting;angels-tin;ingot-tin;item;Tn
Englishmentals;angels-smelting;angels-tin;pellet-tin;item;Tn
Englishmentals;angels-smelting;angels-tin;processed-tin;item;Tn
Englishmentals;angels-smelting;angels-tin;tin-ore;item;Tn
Englishmentals;angels-casting;angels-aluminium-casting;angels-roll-titanium;item;Tt
Englishmentals;angels-casting;angels-titanium-casting;liquid-molten-titanium;fluid;Tt
Englishmentals;angels-casting;angels-titanium-casting;titanium-plate;item;Tt
Englishmentals;angels-smelting;angels-titanium;ingot-titanium;item;Tt
Englishmentals;angels-smelting;angels-titanium;liquid-titanium-tetrachloride;fluid;Tt
Englishmentals;angels-smelting;angels-titanium;pellet-titanium;item;Tt
Englishmentals;angels-smelting;angels-titanium;powder-titanium;item;Tt
Englishmentals;angels-smelting;angels-titanium;processed-titanium;item;Tt
Englishmentals;angels-smelting;angels-titanium;rutile-ore;item;Tt
Englishmentals;angels-smelting;angels-titanium;sponge-titanium;item;Tt
Englishmentals;bio-processing-alien;bio-processing-paste;paste-titanium;item;Tt
Englishmentals;angels-casting;angels-tungsten-casting;casting-powder-tungsten;item;Tu
Englishmentals;angels-casting;angels-tungsten-casting;copper-tungsten-alloy;item;Tu
Englishmentals;angels-casting;angels-tungsten-casting;tungsten-carbide;item;Tu
Englishmentals;angels-casting;angels-tungsten-casting;tungsten-plate;item;Tu
Englishmentals;angels-smelting;angels-tungsten;gas-tungsten-hexafluoride;fluid;Tu
Englishmentals;angels-smelting;angels-tungsten;liquid-tungstic-acid;fluid;Tu
Englishmentals;angels-smelting;angels-tungsten;pellet-tungsten;item;Tu
Englishmentals;angels-smelting;angels-tungsten;powdered-tungsten;item;Tu
Englishmentals;angels-smelting;angels-tungsten;processed-tungsten;item;Tu
Englishmentals;angels-smelting;angels-tungsten;solid-ammonium-paratungstate;item;Tu
Englishmentals;angels-smelting;angels-tungsten;tungsten-ore;item;Tu
Englishmentals;angels-smelting;angels-tungsten;tungsten-oxide;item;Tu
main;intermediate-products;bob-fuel-cells;used-up-thorium-fuel-cell;item;Tx
Englishmentals;resource-refinining;angels-ores;uranium-ore;item;U
main;intermediate-products;bob-fuel-cells;uranium-fuel-cell;item;U
main;resource-refinining;angels-ores;uranium-ore;item;U
main;intermediate-products;bob-nuclear;uranium-235;item;U1
main;intermediate-products;bob-nuclear;uranium-238;item;U1
main;petrochem-refining;petrochem-nitrogen-fluids;gas-urea;fluid;Ur
main;intermediate-products;bob-fuel-cells;used-up-uranium-fuel-cell;item;Ux
main;bio-processing-vegetables;bio-processor-press-vegetables;liquid-vegetable-oil;fluid;VO
Englishmentals;bio-processing-alien;bio-processing-paste;paste-tungsten;item;W
main;angels-casting;angels-tungsten-casting;casting-powder-tungsten;item;W
main;angels-casting;angels-tungsten-casting;copper-tungsten-alloy;item;W
main;angels-casting;angels-tungsten-casting;tungsten-carbide;item;W
main;angels-casting;angels-tungsten-casting;tungsten-plate;item;W
main;angels-smelting;angels-tungsten;gas-tungsten-hexafluoride;fluid;W
main;angels-smelting;angels-tungsten;liquid-tungstic-acid;fluid;W
main;angels-smelting;angels-tungsten;pellet-tungsten;item;W
main;angels-smelting;angels-tungsten;powdered-tungsten;item;W
main;angels-smelting;angels-tungsten;processed-tungsten;item;W
main;angels-smelting;angels-tungsten;solid-ammonium-paratungstate;item;W
main;angels-smelting;angels-tungsten;tungsten-ore;item;W
main;angels-smelting;angels-tungsten;tungsten-oxide;item;W
main;bio-processing-alien;bio-processing-paste;paste-tungsten;item;W
main;bio-processing-nauvis;bio-paper;solid-wood-pulp;item;W
main;bio-processing-nauvis;bio-processing-wood;wood;item;W
main;bio-processing-nauvis;bio-processing-wood;wood-bricks;item;W
main;intermediate-products;bob-boards;wooden-board;item;W
main;water-treatment;water-treatment-fluid;water;fluid;W
main;bio-processing-nauvis;bio-liquor;liquid-white-liquor;fluid;Wt
main;resource-refinining;ore-sorting-fluid;thermal-water;fluid;WT
main;petrochem-refining;petrochem-sodium;solid-sodium-carbonate;item;X1
main;petrochem-refining;petrochem-sodium;solid-sodium-cyanide;item;X2
main;petrochem-refining;petrochem-sodium;solid-sodium-hypochlorite;item;X3
main;petrochem-refining;petrochem-sodium;solid-sodium-chlorate;item;X4
main;petrochem-refining;petrochem-sodium;solid-sodium-perchlorate;item;X5
main;petrochem-refining;petrochem-sodium;sodium-carbonate;item;XC
main;petrochem-refining;petrochem-sodium;solid-sodium-hydroxide;item;XH
main;petrochem-refining;petrochem-sodium;solid-sodium-nitrate;item;XN
main;petrochem-refining;petrochem-sodium;solid-sodium-sulfate;item;XS
Englishmentalsbroken;sct-science;sct-sciencepack-hightech;utility-science-pack;item;Ye
mainbroken;sct-science;sct-sciencepack-hightech;sct-htech-injector;item;Ye
mainbroken;sct-science;sct-sciencepack-hightech;utility-science-pack;item;Ye
main;bio-processing-alien;bio-processing-alien-large;alien-artifact-yellow;item;Ye
main;bio-processing-alien;bio-processing-alien-pre;alien-pre-artifact-yellow;item;Ye
main;bio-processing-alien;bio-processing-alien-small;small-alien-artifact-yellow;item;Ye
main;petrochem-refining;petrochem-catalysts;catalyst-metal-yellow;item;Ye
main;resource-refinining;geode-processing-1;geode-yellow;item;Ye
main;angels-smelting;angels-zinc;cathode-zinc;item;Zn
main;angels-smelting;angels-zinc;ingot-zinc;item;Zn
main;angels-smelting;angels-zinc;pellet-zinc;item;Zn
main;angels-smelting;angels-zinc;processed-zinc;item;Zn
main;angels-smelting;angels-zinc;solid-zinc-oxide;item;Zn
main;angels-smelting;angels-zinc;zinc-ore;item;Zn
main;bio-processing-alien;bio-processing-paste;paste-zinc;item;Zn
main;petrochem-refining;petrochem-chlorine-fluids;liquid-aqueous-sodium-hydroxide;fluid;zz
]]
